#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.23.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.empty(10)

array([4.72617436e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.90943049e-310, 1.91925903e-076, 2.14338723e+184, 5.49702361e-090,
       1.50133995e-076, 6.90947542e-310])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
np.empty(10).size * np.empty(10).itemsize
np.empty(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr = np.full(10 , fill_value = None)
arr[4] = 1
arr

array([None, None, None, None, 1, None, None, None, None, None],
      dtype=object)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.random.randint(10,49,12)
arr

array([46, 20, 47, 44, 39, 10, 34, 25, 18, 25, 15, 34])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(f"The original vector is {arr}")
arr[0] , arr[-1] = arr[-1] , arr[0]
print(f"The reversed vector is {arr}")

The original vector is [1 2 3 4 5 6 7 8]
The reversed vector is [8 2 3 4 5 6 7 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr = np.random.randint(0,8,9).reshape(3,3)
arr

array([[3, 5, 4],
       [0, 6, 4],
       [6, 7, 0]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.array([1,2,0,0,4,0])
np.where(arr == 0)
#np.nonzero(np.array([1,2,0,0,4,0]))

(array([2, 3, 5]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr = np.random.randint(0,27,27).reshape(3,3,3)
arr

array([[[17, 18,  5],
        [23, 18, 16],
        [15,  8,  7]],

       [[25, 19, 21],
        [19, 17, 10],
        [ 7,  8, 20]],

       [[20, 15, 19],
        [23, 25, 24],
        [22,  7, 13]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr = np.random.randint(0,111,100).reshape(10,10)
print(f"The 10x10 array is {arr}")
minimum = np.min(arr)
maximum = np.max(arr)
print(f"The minimum value of the array is {minimum}")
print(f"The maximum value of the array is {maximum}")

The 10x10 array is [[ 94  99  73  47  11  23  55  17  48 105]
 [ 11 100  36  59  35  84  12 105  47  85]
 [ 49  85  77 105  61  71  17  63  69  62]
 [ 80 106  89  18  63  37  51  78  33 100]
 [ 79  11   4   6  80 103  28  12  72  74]
 [ 58 108  98   7   5  23  16  36   2 109]
 [ 20   4  37  89  11  61  10  23  24  42]
 [  7 107 110  66  76  81  86  74  50 107]
 [ 39  71  76  50  27  54  50  75  99  35]
 [ 71  19  93  12  52  72  39  12  58  70]]
The minimum value of the array is 2
The maximum value of the array is 110


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr = np.random.randint(0,99,30)
print(f"The vector is {arr}")
mean = np.mean(arr)
print(f"The mean value is {mean}")

The vector is [16 68 86 94 37 33  8 68 71 20 29 83 48 97 43 28 37 14 95 25  3 44 98 15
 61 52 49 49  2 15]
The mean value is 46.266666666666666


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr = np.zeros(9).reshape(3,3)

arr[0:3 , 0] = 1
arr[0:3 , 2] = 1
arr[0:3:2 , 1:2] = 1

print(arr)

#a = np.ones((10,10))
#a[1:-1,1:-1]=0
#a

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
arr = np.ones(25).reshape(5,5)
arr = np.pad(arr,1)
arr

#a = np.ones((5,5))
#a = np.pad(a,2)
#a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)   # 0
print(np.nan == np.nan) # True
print(np.inf > np.nan)  # True
print(np.nan - np.nan)  # 0
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1) # True

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
arr = np.random.randint(0,25,25).reshape(5,5)
arr = np.diag(np.arange(1,5))
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
arr = np.zeros((8,8))
arr[::2 , ::2 ] = 1
arr[1::2 , 1::2] = 1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
np.tile?

In [ ]:
arr = np.array([[0,1],[1,0]])
checkboard = np.tile(arr,(4,4))
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
arr = np.random.rand(5,5)
mean = np.mean(arr)
standard_deviation = np.std(arr)
Z = mean / standard_deviation

print(f"The original array is {arr}")
print(f"The normalization factor is {Z}")


The original array is [[0.11007827 0.34463414 0.45268555 0.40607711 0.24283254]
 [0.49905148 0.39968847 0.71148853 0.01325341 0.90723217]
 [0.98716175 0.09793216 0.94329314 0.64242383 0.57372093]
 [0.98626091 0.22456715 0.46277077 0.24287479 0.07969716]
 [0.42092106 0.53146524 0.36773272 0.72774085 0.32269345]]
The normalization factor is 1.6665400470736038


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

<ipython-input-24-4daa7c2f2b60>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix1 = np.random.rand(5,3)
matrix2 = np.random.rand(3,2)

print(np.dot(matrix1,matrix2))

[[0.68694516 0.61885422]
 [0.73251442 0.60704388]
 [0.28775627 0.21791644]
 [0.50357093 0.34754124]
 [0.80284046 0.78101336]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.arange(11)
arr[4:8] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
S = sum(range(5))
print(S)
print("First line without importing NumPy --> ",S-1)
print()
print("Second line with NumPy --> ",sum(range(5),-1))

10
First line without importing NumPy -->  9

Second line with NumPy -->  9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.array([0,1,2,3,4])
print(z**z) ### ---> Legal
#print(2 << Z >> 2) ### ---> Not Legal
print(Z <- Z) ### ---> Legal
print(1j*Z) ### ---> Legal
print(Z/1/1) ### ---> Legal
print(Z<Z>Z) ### ---> Legal
z

[  1   1   4  27 256]
False
1.6665400470736038j
1.6665400470736038
False


array([0, 1, 2, 3, 4])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0) # ---> nan
np.array(0) // np.array(0) # ---> 0
np.array([np.nan]).astype(int).astype(float) # ---> nan

<ipython-input-34-7476619d8204>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0) # ---> nan
<ipython-input-34-7476619d8204>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) # ---> 0


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(arr)), arr))

[-5.  3.  5. -3.  1. -2.  7. -1.  9. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
matrix1 = np.array([1,2,3,5,7,11])
matrix2 = np.array([1,3,5,7,8,11])

print(np.intersect1d(matrix1,matrix2))

[ 1  3  5  7 11]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
##import warnings
##warnings.filterwarnings('ignore')

data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])

/usr/local/lib/python3.10/dist-packages/numpy/lib/nanfunctions.py:1217: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
np.datetime_data?
np.datetime64?

In [ ]:
yesterday = np.datetime64('today' , 'D') - np.timedelta64(1 , 'D')
today = np.datetime64('today' , 'D')
tomorrow = np.datetime64('today' , 'D') + np.timedelta64(1 , 'D')

print(f"Yesterday date is {yesterday}")
print(f"Today date is {today}")
print(f"Tomorrow date is {tomorrow}")

Yesterday date is 2023-10-05
Today date is 2023-10-06
Tomorrow date is 2023-10-07


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
np.add?

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B) # (A+B) stored in B
np.divide(A,2,out=A) # (A/2) stored in A
np.negative(A,out=A) # (A*-1) stored in A
np.multiply(A,B,out=A) # B[A+B] * A[[A+B],[(A*-1)]] ---> computed in place

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = np.random.uniform(3,11,10)

print(f"Original array is {arr}")
print()
print(f"floor method: {np.floor(arr)}")
print()
print(f"round method: {np.round(arr)}")
print()
print(f"astype method: {arr.astype(int)}")
print()
print(f"ceil method: {np.ceil(arr)}")

Original array is [ 3.40362822  6.32065137  9.37672591  3.26769994  7.7895469   7.06394593
  5.21991393  9.09684587 10.40072271  9.49169693]

floor method: [ 3.  6.  9.  3.  7.  7.  5.  9. 10.  9.]

round method: [ 3.  6.  9.  3.  8.  7.  5.  9. 10.  9.]

astype method: [ 3  6  9  3  7  7  5  9 10  9]

ceil method: [ 4.  7. 10.  4.  8.  8.  6. 10. 11. 10.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr = np.zeros((5,5))
arr[0:,1] = 1
arr[0:,2] = 2
arr[0:,3] = 3
arr[0:,4] = 4
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
from numpy.core.multiarray import nditer
def generator():
  arr = np.array([])
  for x in range(10):
    arr = np.append(arr,x)
  return arr

matrix = np.array([generator()])
matrix

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = np.random.rand(10)
print(f"Original array is {arr}")
print()
arr.sort()
print()
print(f"The sorted array is {arr}")

Original array is [0.35291127 0.26527144 0.47603146 0.31027519 0.68840008 0.41063651
 0.35763027 0.2376268  0.20453581 0.3001309 ]


The sorted array is [0.20453581 0.2376268  0.26527144 0.3001309  0.31027519 0.35291127
 0.35763027 0.41063651 0.47603146 0.68840008]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = np.array([1,2,3,4])
sum = np.add.reduce(arr)
sum

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.rand(10)
B = np.random.rand(10)
print(np.array_equal(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
A = np.random.rand(10)
A.flags.writeable = False
print(A)
A[1] = 0  ### --> Immutable

[0.12840493 0.40891738 0.56220513 0.09123534 0.15567355 0.43903708
 0.46357541 0.99975951 0.1000845  0.52955719]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.55972955 0.48549629 0.995458   0.41922916 0.95252644 0.6181802
 0.85678746 0.75483836 0.54119658 1.15848303]
[1.06124137 0.91750355 1.2731638  1.48251167 0.76941701 0.18793499
 0.88499304 0.99668946 1.34435422 1.00633455]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
arr = np.random.rand(10)
arr.sort()
print(f"The original vector is: {arr}")
print()
arr[-1] = 0
print(arr)

The original vector is: [0.04284198 0.07989336 0.1222417  0.1268101  0.17681584 0.17926876
 0.23110032 0.54650753 0.5842968  0.77077412]

[0.04284198 0.07989336 0.1222417  0.1268101  0.17681584 0.17926876
 0.23110032 0.54650753 0.5842968  0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.inf)
arr = np.eye(10)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
arr = np.arange(100)
print(f"Original array: {arr}")
print()
value = np.random.uniform(0,100)
print(f'The value is: {value}')
print()
index = (np.abs(arr-value)).argmin()
print(arr[index])

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

The value is: 23.629670541534498

24


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
arr = np.ones(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(arr)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


/usr/local/lib/python3.10/dist-packages/numpy/core/numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import scipy
import scipy.spatial

arr = np.random.random((100,2))
distance = scipy.spatial.distance.cdist(arr,arr)
print(distance)

[[0.         0.56013763 0.68867412 0.3587942  0.7195697  0.66526117
  0.7434881  0.5919548  0.7915637  0.38250993 0.52759917 0.15025055
  0.74318815 0.43716445 1.0223441  0.02752393 0.85574483 0.77819296
  0.8518517  0.83251849 0.32392738 0.73886693 0.74864756 0.36492942
  0.28506534 0.59247279 0.66505244 0.9598384  0.59296462 0.0965227
  0.6519577  0.67696215 0.82487048 0.574077   0.7368669  0.71927522
  0.4107107  0.75256064 0.87650803 0.54944784 0.57431313 0.45156678
  0.32921687 0.83312094 0.57597311 0.28828605 0.35017745 0.20786029
  0.14878723 0.62920071 0.4982121  0.79370645 0.63156162 0.51066474
  0.62484087 0.41565259 0.53759483 0.52981608 0.71628391 0.24608819
  0.71304057 0.97491292 0.68900836 0.80889907 0.4167785  0.92754507
  0.35055158 0.74082806 0.77968827 0.75343193 0.29981213 0.87889275
  0.34738508 0.41018898 0.57763372 0.16057364 0.22796376 0.08756086
  0.13601535 0.80741913 0.31085921 0.10477363 0.71998369 0.34248507
  0.85389334 0.86711451 0.48742679 0.39511554 0.6

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
arr = np.arange(10, dtype=np.float32)
arr = arr.astype(np.int32)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

file_data = StringIO("""1, 2, 3, 4, 5\n
                        6,  ,  , 7, 8\n
                         ,  , 9,10,11\n""")

read = np.genfromtxt(file_data, delimiter=',', dtype=np.int)
read

<ipython-input-65-cae4b0f84bea>:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  read = np.genfromtxt(file_data, delimiter=',', dtype=np.int)


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr = np.arange(12).reshape(3,4)

for index, value in np.ndenumerate(arr):
    print(index, value)

print()
print("===================================================")
print()

for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11


(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False),1)
print(arr)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
arr = np.random.rand(5, 10)
newarr = arr - arr.mean(axis=1).reshape(-1, 1)

print(newarr)

[[-0.46939141  0.06809873  0.30283855  0.35798496 -0.47359084  0.01751641
  -0.29704705  0.08598015  0.29553093  0.11207956]
 [ 0.2946654   0.25887615  0.12678016  0.09258852 -0.23897781  0.16849574
  -0.01962173 -0.16342863 -0.02242086 -0.49695695]
 [ 0.29393074 -0.16711176 -0.33146657  0.18596979  0.33539059  0.08549556
  -0.39133809  0.23022941 -0.54059242  0.29949274]
 [ 0.11754633  0.39013737 -0.03294152 -0.23198178 -0.30809525 -0.15091732
   0.38794315  0.04698749 -0.06659316 -0.1520853 ]
 [ 0.13960703 -0.09597345 -0.00511217  0.26976474  0.23551728  0.00270321
   0.16094828  0.09970195 -0.54092907 -0.2662278 ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[2 6 0]
 [4 6 7]
 [5 1 6]]
[[5 1 6]
 [2 6 0]
 [4 6 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
arr = np.random.randint(0,3,(3,10))
print((~arr.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
arr = np.random.rand(9).reshape(3,3)
arr

value = 0.5
N = arr.flat[np.abs(arr-value).argmin()]

print(f'Nearest value to {value} is {N}')

Nearest value to 0.5 is 0.483022937867817


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
matrix1 = np.random.rand(3).reshape(1,3)
matrix2 = np.random.rand(3).reshape(3,1)

print(f'1x3 array is: {matrix1}')
print()
print(f'3x1 array is: {matrix2}')

iterator = np.nditer([matrix1,matrix2,None])

for x,y,z in iterator: z[...] = x+y
print()
print(f'Sum result is: {iterator.operands[2]}')

1x3 array is: [[0.15137386 0.68878399 0.06213573]]

3x1 array is: [[0.54508824]
 [0.99482186]
 [0.6632064 ]]

Sum result is: [[0.69646209 1.23387222 0.60722397]
 [1.14619572 1.68360584 1.05695759]
 [0.81458026 1.35199039 0.72534213]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class Array(np.ndarray):

    def __new__(cls, array, name="name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "name")

Z = Array(np.arange(10), "Array_10")
print (Z.name)

Array_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
vector1 = np.ones(10)
vector2 = np.random.randint(0,len(Z),20)

vector1 += np.bincount(vector2, minlength=len(Z))
print(vector1)

# Another solution

np.add.at(vector1, vector2, 1)
print(vector1)

[3. 3. 3. 3. 2. 5. 3. 4. 3. 1.]
[5. 5. 5. 5. 3. 9. 5. 7. 5. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
arr = np.random.randint(0,10,(3,4,3,4))
sum = arr.sum(axis=(-2,-1))
print(sum)

[[63 63 57 46]
 [58 68 77 40]
 [59 37 52 49]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.66396328 0.60211474 0.51442931 0.54042751 0.52513936 0.45052313
 0.51999812 0.50358041 0.36027665 0.59980076]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
matrix1 = np.random.uniform(0,10,(3,3))
matrix2 = np.random.uniform(0,10,(3,3))

np.diag(np.dot(matrix1,matrix2))

array([89.62122413, 71.28333928, 95.79518375])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
vector = np.array([1,2,3,4,5])
zeros = 3
vector_0 = np.zeros(len(vector) + (len(vector)-1)*(zeros))
vector_0[::zeros+1] = Z
print(vector_0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
arr = np.ones((5,5,3))
new_arr = 2*np.ones((5,5))
print(arr * new_arr[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
arr = np.arange(25).reshape(5,5)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
np.roll?
np.repeat?

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(17, 90) (17, 91) (22, 48) (22, 85) (26, 45) (26, 53) (28, 67) (28, 85)
 (33, 50) (33, 53) (33, 58) (33, 84) (37, 59) (37, 76) (37, 92) (37, 93)
 (45, 53) (48, 85) (50, 84) (53, 58) (59, 76) (67, 85) (70, 86) (70, 95)
 (77, 78) (77, 91) (78, 91) (86, 95) (90, 91) (92, 93)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
np.bincount?

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
np.cumsum?

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
arr = np.arange(20)
print(moving_average(arr, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def roll(arr, window):
    shape = (arr.size - window + 1, window)
    strides = (arr.itemsize, arr.itemsize)
    return stride_tricks.as_strided(arr, shape=shape, strides=strides)
arr = roll(np.arange(10), 3)
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
matrix = np.random.randint(0,2,100)
np.logical_not(matrix, out=matrix)

matrix = np.random.uniform(-1.0,1.0,100)
np.negative(matrix, out=matrix)

array([ 0.3389448 , -0.17176772,  0.38548298, -0.67794062, -0.74777157,
        0.09824573, -0.10874739,  0.52650745,  0.52416193,  0.73956239,
        0.51409249, -0.34246342, -0.48913998,  0.64753646,  0.89267501,
        0.55053851, -0.85191731, -0.08290893,  0.20539819, -0.80006219,
       -0.61278393, -0.34259807,  0.20413003, -0.45647486, -0.90425076,
        0.33536261, -0.76300707, -0.67766874, -0.68941373,  0.8233938 ,
       -0.62934685,  0.30130587, -0.56350416,  0.25488616,  0.78442725,
        0.03889743,  0.21277685,  0.79165208, -0.4161467 , -0.75387135,
        0.70490185,  0.58791298, -0.47475116, -0.96745429,  0.75336854,
       -0.35474041,  0.45887019,  0.67477915, -0.99424967,  0.26516763,
        0.07695277, -0.12257511, -0.3060881 , -0.58685572,  0.97806552,
        0.44253637,  0.81190263, -0.59331056,  0.36277659, -0.27713771,
       -0.34402992, -0.83437804, -0.72100549, -0.39295924,  0.17426871,
        0.46943452,  0.40185782, -0.06590064,  0.60789946,  0.65

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[9.2497954  1.0409652  5.30746407 4.59148174 1.35864192 2.27136793
 7.69512422 5.93567532 1.4386645  1.60753162]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 8.17509217 11.41329274  4.10077718  6.22084443  3.96986076 12.3836166
  12.5329227   9.93684029 14.61379364  5.19176504]
 [ 1.03724553  4.31862299  2.84237664  0.94552642  1.65406745  8.25635982
   8.9176529   3.0526054   9.68054992 11.27122024]
 [ 3.32683548  2.15223761  6.01293987  6.85998561 10.5092735   0.96874254
   0.27250149  4.21285655  0.54847208 11.73766814]
 [ 5.18555885  2.2978846   8.67817836  7.50317028  7.652337    3.30306551
   4.35448085  3.56713476  4.14304715 15.91403188]
 [ 7.09436018  6.98761054  4.73766892  2.72735684  5.39201456  1.22951612
   1.01944173  4.09246163  4.25803234  1.00525726]
 [ 0.20170802  3.51378305  3.66804051  1.76597511  2.24727391  7.85379656
   8.57836436  2.28349713  9.17659787 12.02194058]
 [ 4.33276649  7.96709597  0.17543212  2.63112686  1.88934565 11.33338009
  11.80689991  6.76531043 13.02729109  9.03255917]
 [ 6.44903737  4.72363103  4.92723223  0.9134554  10.02060014  4.24113844
   4.61644168  1.14524656  0.83990914  0.91756174]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
#R[r] = Z[z]
print(Z)
print(R)

[[5 9 3 5 3 5 3 7 4 9]
 [5 2 4 4 0 1 9 6 1 1]
 [6 4 7 2 9 8 0 1 4 6]
 [0 8 3 8 3 6 3 9 3 0]
 [5 0 1 9 4 2 8 6 1 9]
 [2 7 5 6 0 8 2 9 1 4]
 [6 7 1 6 8 8 1 1 0 3]
 [6 2 2 0 7 5 0 5 2 3]
 [3 2 4 4 5 3 2 9 9 5]
 [9 4 3 2 3 7 5 7 0 4]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
matrix = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(matrix) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [ ]:
arr = np.random.randint(0,10,50)
print(f"The array is: {arr}")
print(f"The most frequent value is: {np.bincount(arr).argmax()}")

The array is: [7 8 7 4 9 4 7 0 6 6 8 1 8 7 3 8 1 6 3 7 5 6 3 3 7 2 3 2 8 6 8 8 0 1 1 8 2
 2 1 9 2 6 0 7 5 1 8 4 1 7]
The most frequent value is: 8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
arr = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
C = stride_tricks.as_strided(arr, shape=(i, j, n, n), strides=arr.strides + arr.strides)
print(C)

[[[[1 3 0]
   [3 4 3]
   [0 3 0]]

  [[3 0 2]
   [4 3 4]
   [3 0 1]]

  [[0 2 1]
   [3 4 0]
   [0 1 1]]

  [[2 1 4]
   [4 0 1]
   [1 1 0]]

  [[1 4 2]
   [0 1 1]
   [1 0 4]]

  [[4 2 4]
   [1 1 0]
   [0 4 1]]

  [[2 4 3]
   [1 0 3]
   [4 1 0]]

  [[4 3 3]
   [0 3 2]
   [1 0 1]]]


 [[[3 4 3]
   [0 3 0]
   [4 3 3]]

  [[4 3 4]
   [3 0 1]
   [3 3 3]]

  [[3 4 0]
   [0 1 1]
   [3 3 1]]

  [[4 0 1]
   [1 1 0]
   [3 1 1]]

  [[0 1 1]
   [1 0 4]
   [1 1 0]]

  [[1 1 0]
   [0 4 1]
   [1 0 1]]

  [[1 0 3]
   [4 1 0]
   [0 1 3]]

  [[0 3 2]
   [1 0 1]
   [1 3 4]]]


 [[[0 3 0]
   [4 3 3]
   [0 0 1]]

  [[3 0 1]
   [3 3 3]
   [0 1 0]]

  [[0 1 1]
   [3 3 1]
   [1 0 4]]

  [[1 1 0]
   [3 1 1]
   [0 4 0]]

  [[1 0 4]
   [1 1 0]
   [4 0 4]]

  [[0 4 1]
   [1 0 1]
   [0 4 0]]

  [[4 1 0]
   [0 1 3]
   [4 0 0]]

  [[1 0 1]
   [1 3 4]
   [0 0 1]]]


 [[[4 3 3]
   [0 0 1]
   [1 1 2]]

  [[3 3 3]
   [0 1 0]
   [1 2 0]]

  [[3 3 1]
   [1 0 4]
   [2 0 2]]

  [[3 1 1]
   [0 4 0]
   [0 2 3]]

  [[1 1 0]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  8 13 10 14]
 [ 8  2 10 15  6]
 [13 10  8 42  5]
 [10 15 42  4  9]
 [14  6  5  9  7]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 4 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 1 1]
 [2 1 4]
 [3 2 1]
 [0 4 1]
 [1 1 4]
 [0 1 1]
 [4 1 3]
 [0 0 4]
 [0 0 3]
 [4 3 0]]
[[4 1 1]
 [2 1 4]
 [3 2 1]
 [0 4 1]
 [1 1 4]
 [0 1 1]
 [4 1 3]
 [0 0 4]
 [0 0 3]
 [4 3 0]]
[[4 1 1]
 [2 1 4]
 [3 2 1]
 [0 4 1]
 [1 1 4]
 [0 1 1]
 [4 1 3]
 [0 0 4]
 [0 0 3]
 [4 3 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[6.88023266e-01, 3.03370404e-01, 6.22099834e-01, 5.27741005e-01,
        6.89633738e-01, 2.41716905e-01, 6.47726240e-01, 7.43788395e-01,
        3.78895387e-01, 5.24550984e-04],
       [2.10551706e-01, 9.28386571e-02, 1.90377546e-01, 1.61501470e-01,
        2.11044549e-01, 7.39712001e-02, 1.98219844e-01, 2.27617179e-01,
        1.15951122e-01, 1.60525247e-04],
       [3.49406061e-01, 1.54063770e-01, 3.15927474e-01, 2.68008242e-01,
        3.50223924e-01, 1.22753628e-01, 3.28941601e-01, 3.77725851e-01,
        1.92418413e-01, 2.66388220e-04],
       [1.73689534e-01, 7.65850034e-02, 1.57047350e-01, 1.33226729e-01,
        1.74096093e-01, 6.10207514e-02, 1.63516664e-01, 1.87767284e-01,
        9.56510724e-02, 1.32421417e-04],
       [5.65394166e-01, 2.49299501e-01, 5.11220527e-01, 4.33679645e-01,
        5.66717597e-01, 1.98634748e-01, 5.32279438e-01, 6.11220056e-01,
        3.11363368e-01, 4.31058193e-04],
       [8.69193296e-01, 3.83253786e-01, 7.85910930e-01, 6.66705570e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.19876787  0.1769086 ]
